env_setting:
  num_gpus: 1
  num_workers: 4
  seed: 1234
  stdout_interval: 200
  checkpoint_interval: 4000
  validation_interval: 2000
  summary_interval: 200
  dist_cfg:
    dist_backend: nccl
    dist_url: tcp://localhost:29531
    world_size: 1

data_cfg:
  train_clean_json: data/train_clean.json
  train_noisy_json: data/train_noisy.json
  valid_clean_json: data/test_clean_all.json
  valid_noisy_json: data/test_noisy_all.json
  test_clean_json: data/test_clean.json
  test_noisy_json: data/test_noisy.json

training_cfg:
  training_epochs: 400
  batch_size: 2
  learning_rate: 0.0009
  adam_b1: 0.8
  adam_b2: 0.99
  max_grad_norm: 5.0
  lr_decay: 0.99
  segment_size: 30600
  loss:
    metric: 0.05
    magnitude: 0.9
    phase: 0.3
    complex: 0.1
    time: 0.2
    consistancy: 0.1
  use_PCS400: false

stft_cfg:
  sampling_rate: 16000
  n_fft: 510
  hop_size: 120
  win_size: 510

model_cfg:
  hid_feature: 16
  dense_channel: 16
  compress_factor: 0.3
  num_tfmamba: 2
  d_state: 16
  d_conv: 4
  expand: 4
  norm_epsilon: 0.00001
  phase_eps: 0.001
  complex_residual_scale: 0.1
  complex_residual_gate_bias: -2.0
  beta: 2.0
  input_channel: 2
  output_channel: 1
  cross_pool_t: 2
  cross_pool_f: 2
  cross_sparse_window: 64
  cross_global_window: 8
  cross_sparsity: 0.9
  num_mid_pairs: 3
  uils_enabled: true
